policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        invalidLastCharacters: .
      body:
        required: true
      dco: true
      spellcheck:
        locale: US
      conventional:
        types:
          - "chore"
          - "refactor"
        scopes:
          - "scope"
        descriptionLength: 72
