name: Release

permissions:
  contents: write
on:
  push:
    tags:
      - v*

env:
  EXTRA_NIX_FLAGS: --log-format raw-with-logs --print-build-logs

jobs:
  x86_64-linux---release:
    name: Build release artifacts for x86_64-linux
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        system:
          # TODO make this work well
          # - "aarch64-linux"
          - x86_64-linux
        pkg: [release-package]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: dlr-ft
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - id: supported-system
        name: Skip unsupported builds
        run: $(nix eval --json .#packages.${{ matrix.system }}.${{ matrix.pkg }}.meta.available)
      - if: steps.supported-system.conclusion == 'success'
        run:
          nix build $EXTRA_NIX_FLAGS .#packages.${{ matrix.system }}.${{ matrix.pkg
          }}
      - if: steps.supported-system.conclusion == 'success'
        name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: ${{ contains(github.ref_name, 'rc') }}
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') }}
          files: result/*
